/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2023-07-11 09:26:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1686318168070L));
    _jspx_dependants.put("jar:file:/C:/Users/Home/Desktop/JAVA_WEB/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/new-jdbc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Users/Home/Desktop/JAVA_WEB/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/new-jdbc/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686063678958L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1686063679124L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h1 class=\"my-4\">Category</h1>\r\n");
      out.write("\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Sports</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"list-group-item\">Worlds</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"list-group-item\">Politics</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"list-group-item\">News</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"list-group-item\">Views</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-3 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-lg-9\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"carouselExampleIndicators\" class=\"carousel slide my-4\"\r\n");
      out.write("\t\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"d-block img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://academics.siu.edu/computing-and-technology/_common/images/itec/itec-index-banner.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"First slide\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"d-block img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://mendoza.nd.edu/wp-content/uploads/2021/01/bits-e1611847851285-1440x810.jpeg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Second slide\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"d-block img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://www.analyticsinsight.net/wp-content/uploads/2022/09/Java-19-comes-with-an-open-source-twist-All-you-need-to-know.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Third slide\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t</a> <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/cuoc-thi-giai-thuat-toan-voi-tong-giai-thuong-hang-tram-trieu-dong-c55a1482666.html\"><img\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://icdn.24h.com.vn/upload/3-2023/images/2023-07-10/255x170/code-1688964372-832-width740height555_anh_cat_3_2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/cuoc-thi-giai-thuat-toan-voi-tong-giai-thuong-hang-tram-trieu-dong-c55a1482666.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCuộc thi giải thuật toán với tổng giải thưởng hàng trăm triệu\r\n");
      out.write("\t\t\t\t\t\t\t\t\tđồng</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">Thí sinh được yêu cầu giải các bài toán\r\n");
      out.write("\t\t\t\t\t\t\t\tvề thuật toán và thể hiện tư duy giải quyết vấn đề trong...</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/sieu-bao-mat-troi-lieu-co-khien-internet-sap-toan-cau-c55a1482571.html\"><img\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://icdn.24h.com.vn/upload/3-2023/images/2023-07-10/255x170/adt1688951454-sun-1688895256082789919003_anh_cat_3_2.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/sieu-bao-mat-troi-lieu-co-khien-internet-sap-toan-cau-c55a1482571.html\">Siêu\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbão Mặt trời năm 2025 liệu có khiến Internet \"sập\" toàn cầu?</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">Có hay không khả năng xảy ra \"Ngày tận\r\n");
      out.write("\t\t\t\t\t\t\t\tthế Internet\" do Siêu bão Mặt trời gây ra, đã thu hút sự chú...</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://icdn.24h.com.vn/upload/3-2023/images/2023-07-09/255x170/adt1688897659-tien-ao-9044_anh_cat_3_2.jpeg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Chuyên gia điểm mặt kiểu lừa đảo \"học thức\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttrong lĩnh vực blockchain</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">Có một số đối tượng thành lập công ty\r\n");
      out.write("\t\t\t\t\t\t\t\ttrong lĩnh vực blockchain đặt dưới hình thức công ty nước...</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/microsoft-phu-nhan-de-ro-ri-thong-tin-30-trieu-khach-hang-c55a1482749.html\"><img\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://icdn.24h.com.vn/upload/3-2023/images/2023-07-10/255x170/adt1688977094-microsoft-22_anh_cat_3_2.jpeg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/microsoft-phu-nhan-de-ro-ri-thong-tin-30-trieu-khach-hang-c55a1482749.html\">Microsoft\r\n");
      out.write("\t\t\t\t\t\t\t\t\tphủ nhận để rò rỉ thông tin 30 triệu khách hàng</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">Microsoft đã bác bỏ tuyên bố của nhóm\r\n");
      out.write("\t\t\t\t\t\t\t\thacker về việc chúng đã đánh cắp thông tin đăng nhập của 30...</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/mang-5g-tuy-nhanh-nhung-van-co-mot-nhuoc-diem-dang-lo-ngai-c55a1482033.html\"><img\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://icdn.24h.com.vn/upload/3-2023/images/2023-07-07/255x170/5g-1688714536-889-width740height555_anh_cat_3_2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/mang-5g-tuy-nhanh-nhung-van-co-mot-nhuoc-diem-dang-lo-ngai-c55a1482033.html\">Mạng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t5G tuy nhanh, nhưng vẫn có một nhược điểm đáng lo ngại</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">Một nghiên cứu mới chỉ ra rằng mạng 5G\r\n");
      out.write("\t\t\t\t\t\t\t\tlà “kẻ thù” của pin điện thoại, thậm chí còn hơn cả mạng 4G.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/chatgpt-dang-buoc-den-bo-vuc-suy-tan-c55a1481763.html\"><img\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://icdn.24h.com.vn/upload/3-2023/images/2023-07-06/255x170/thumb-1688634162-303-width740height555_anh_cat_3_2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://www.24h.com.vn/cong-nghe-thong-tin/chatgpt-dang-buoc-den-bo-vuc-suy-tan-c55a1481763.html\">ChatGPT\r\n");
      out.write("\t\t\t\t\t\t\t\t\tđang bước đến bờ vực suy tàn?</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">Từng là dịch vụ phát triển nhanh nhất từ\r\n");
      out.write("\t\t\t\t\t\t\t\ttrước đến nay với 1,5 tỷ người truy cập hàng tháng, nhưng...</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-9 -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.row -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
